### ISSUE TITLE
prepare_fullDCM throws an error when using only Gaussian sources.

### ISSUE THREAD

**Issue by SRSteinkamp** [MBB-team/VBA-toolbox#20]
Dear all, 

I found that, when using only Gaussian source in prepare_fullDCM, line 99 throws an error, as  (1:sum([sources.type]~=0)) returns an empty 1x0 matrix:

inG.indr = inG.ind2(end) + (1:sum([sources.type]~=0));

Additionally, there will be no unique offset parameters for other Gaussian observational sources.

Best,
Simon

**Comment by jdaunize** [comment]
Dear Simon,
May I ask you to post your comment on VBA's forum: http://mbb-team.github.io/VBA-toolbox/forum/ ?
We will then answer your query...
Thank you!
Best,
Jean.

**Comment by lionel-rigoux** [comment]
The bug has already been discussed in the forum. I asked Simon to also flag it here so we can keep track of the issue (and of when it is solved) directly in the commit history.

**Comment by lionel-rigoux** [comment]
Originally, the decoding function was supposed to be:
- a softmax for binary response, with one parameter (the temperature)
- the identity for gaussian responses (no parameters)

However, 1) the temperature is correlated with the behavioural mapping parameters, and 2) for all sources we need an additional parameter to offset the behavioural response by an offset.

The new default will then be set to the number of sources minus one (source number one being the BOLD response).

For more complex observation functions, inG.indr and dim.n_phi need to be set by hand by the user.
