### ISSUE TITLE
Undocumented functions

### ISSUE THREAD

**Issue by lionel-rigoux** [MBB-team/VBA-toolbox#27]
A set of functions in the root directory are undocumentemented:

- ~VBA_dcmMatrices~ (7219f2753dfd4a5bdc8fef4d6d5493e4f9e432f1)
- ~VBA_get_dL~ (ead1bc35f9bab34db308108647daa9b35cf987a8)
- ~VBA_get_tracker~ (a866b859f1c83ea67da871e388c03f94283e13df)
- ~VBA_multisession_expand~ (4541e05ba3f038144f518ee58da276982a8a71d7)
- ~VBA_multisession_factor~ (4541e05ba3f038144f518ee58da276982a8a71d7)
- ~VBA_optimPriors~ (already documented)
- ~VBA_setup~ (ef43b3323df31e547fe54b1bc876a49148ddeadb)
- ~VBA_Shapley~
- VBA_susceptibility
- ~VBA_version~ (a866b859f1c83ea67da871e388c03f94283e13df)
- ~factorial_struct~ (355d3745225b2ee06e14ddb84ada740ab188ccb1)
- ~getHyperpriors~ (now VBA_guessHyperpriors)
- getStateParamInput
- setInputs
- setPriors
- ~check_struct~ (81d7c9df466aa881aa8bb818e55d3a72f8d4c45c)

**Comment by jdaunize** [comment]
Note: the function 'check_struct' seems to be quite overloaded. If i'm correct, it is now in the subfolder 'subfunctions'. But in fact, VBA would not run without it (cf. VBA_check, VBA_fiinPriors, etc...). It may be good to rename it VBA_checkstruct and move it to the core directory (with proper header)?
