### ISSUE TITLE
extended and multisource

### ISSUE THREAD

**Issue by lionel-rigoux** [MBB-team/VBA-toolbox#28]
There are some redundancies in the core and display code to process differentially single or multi-sources data. Part of the switches between these two trails relies on the number of sources, some on an "extended" flag in the options structure. The latter was introduced to test the equivalence of the processing of single source models accross the two versions of codes. Therefore, this flag is not reliable to indicate the number of sources and only add unecessary redundancy in the instructions workflow.
I think the redundancy should be reduced to its minimum and the "extended" flag should be removed. In particular, this concerns the following functions:

- VBA_initDisplay.m / VBA_initDisplay_extended.m
- VBA_updateDisplay.m / VBA_updateDisplay_extended.m

Part of the redundancy is however required has the treatment of stochastic and multisources models cannot be yet fused (cf. VBA_Iphi.m)

**Comment by jdaunize** [comment]
Hey Lionel,
I agree. I'll remove the 'extended' field where I know it is, namely:
- in VBA_check
- in display functions VBA_initDisplay and VBA_updateDisplay (where I'll simply check the number of sources).
Any other idea?
J.

**Comment by jdaunize** [comment]
Oh and also in VBA_GN...

**Comment by lionel-rigoux** [comment]
I don't have it all in mind, but an advanced search for text in matlab should be able to point to all occurences of the flag.

Concerning the display, I will take care of merging (respectively for init and update) the two versions into a unique versatile function. Having said that, you could still replace the extended flag by a source number check, it yon't hurt!

**Comment by lionel-rigoux** [comment]
Well, the flag should be in all places the multisource can kick in. I used this flag to extensively check  single source models that the old code (single source) and the new one (intended for multisource but activated by the flag) gace strictly identical results.

**Comment by jdaunize** [comment]
So i've been replacing the 'extended' flag with a check on the number of sources everywhere I've seen it.
I've ran a number of demos, and it all looks fine. I'll commit soon.

**Comment by jdaunize** [comment]
Re: multi-source display: I'm kind of unhappy here, because it systematically cracks with me.
Besides, I think it should be optimized because the current version will look really crap if the number of sources incerases...

**Comment by lionel-rigoux** [comment]
What do you mean "cracks"?
I went up to a dozen sources without problems. A scroll appears on the right to navigate through the sources when it doesn't fit the panel. Having said that, I have no strong feeling about this!

**Comment by jdaunize** [comment]
:)
When I navigate through the tabs, it cracks...

**Comment by jdaunize** [comment]
Here is a series of screen captures:
[bugs_VBA.pptx](https://github.com/MBB-team/VBA-toolbox/files/1080442/bugs_VBA.pptx)

The 2 first ones ar eduring the inversion:
- 1) the top axes are not well positioned
- 2) when I scroll down with the slidebar, the bottom axis has scrambled legend and labels

The 2 last ones are after VBA convergence:
- 1) OK
- 2) I navigate through the tabs: 'inversion', 'diagnostic' and then... it cracks :(

**Comment by lionel-rigoux** [comment]
Ok I found the problem:

**Comment by lionel-rigoux** [comment]
We need to find a better selector to retrieve the handle to the pane correctly irrespective of the Matlab version. Moreover, I really need to merge those display functions as those kind of half bug corrections are quite nasty to identify.

**Comment by lionel-rigoux** [comment]
And the axes ill positioned,  it is also related to  the change of the status of panel in the graphical hierarchical. A quick workaround would be to add an offset depending on the graphical engine version.

**Comment by lionel-rigoux** [comment]
We can start there:
https://de.mathworks.com/help/matlab/graphics-changes-in-r2014b.html

**Comment by lionel-rigoux** [comment]
Solved by pull request #32
