### ISSUE TITLE
Demo failings

### ISSUE THREAD

**Issue by lionel-rigoux** [MBB-team/VBA-toolbox#33]
| demo                     | 13 | 14       | 16 | 17 | reason |
|:-------------------------|:---|:---------|:---|:---| :-|
| 'demo_2DChoices'           | ?  | 🐞 | 😸   | ?  |  relies on ´quantile´ |
| 'demo_BSL'                      | 😸  | 😸   | 😸   | ?  |  fixed by d1a65174525b6008896e8e2620fc7b39fe0e0721 and by 905e04f24639d93bb5942214791045fb11e7a4ec|
| 'demo_CI'                       | ?  | 🐞  | 😸   | ?  |  relies on ´prctile´ from stats toolbox|
| 'demo_CaBBI_FHN'         | ?  | 🐞  | 😸   | ?  |  relies on data fitting toolbox (fittype)  |
| 'demo_CaBBI_QGIF'        | ?  | 🐞  | 😸   | ?  |  relies on data fitting toolbox (fittype) |
| 'demo_HRF_distributed'   | 😸  | ?| 😸   | ?  |  fixed by a8550d9b7874123338b22a100a9bdc4b5efaccc2 |
| 'demo_MFX'                     |  ?  | 🐞  | 😸   | ?  | utilises `cdf` which depends on the stats toolbox |
| 'demo_ToMgames'          | ?  | 😸  | 😸     | ?  |  plot problem + bug in multinomial sampling, fixed by d1a65174525b6008896e8e2620fc7b39fe0e0721|
| 'demo_bmc4glm'           | ?  | 🐞  | 😸   | ?  | utilises `cdf` which depends on the stats toolbox   |
| 'demo_classification'    | 😸  | 😸  | 😸   | ?  | dependency on zscore. Fixed by bc3e13162224663e3ea34fcc1563c54c9675328e |
| 'demo_dcm_motorPremotor' | 😸  | ?  |😸    | ?  | fixed by 50c7aef250187d42f622a83178f92e1a0c21e90e |
| 'demo_dcmonline'         | 😸  | 😸  | 😸   | ?  |  fixed by 57a9a8159eb5114aa67146fad5c6d2c57771be75 |
| 'demo_dynLearningRate'   | ?  | 🐞  | 😸   | ?  | utilises `cdf` which depends on the stats toolbox |
| 'demo_interaction'       | 😸  | 😸  |  😸  | 😸  |  fixed (removed) by f7ec4433b366ec05b926f33321b65b13b2561110  |
| 'demo_nullSpace'         | 😸  | 😸  |  😸  | 😸  |  fixed (removed) by 8a6f9e6b5ef41458b342e788276176a44f8c3a8d |
| 'demo_spm_hrf'           | 😸  | 😸  |  😸  | 😸  |   fixed (removed) by a8af462a40bb8998619442970c54f7fd7260b28a |
| 'demo_susceptibility'    | 😸  | 🐞  | 😸    | ?  |  demo outdated + stochastic bug|
| 'demo_test'              | 😸  | 😸  |  😸  | 😸  |  fixed (removed) by a7abf61c6999a679c1b811bc3af844782dcd178e |

**Comment by jdaunize** [comment]
All the bug fixes performed under MATLAB 2013 need to be checked for other MATLAB versions!

**Comment by jdaunize** [comment]
Note: 'demo_susceptibility' runs OK on MATLAB 2013.

**Comment by lionel-rigoux** [comment]
solved by 0b371688aa378d69ffe2ae2367fe17750e21b02d
