### ISSUE TITLE
VBA_MFX is slowing down

### ISSUE THREAD

**Issue by awiehler** [MBB-team/VBA-toolbox#46]
Hi,
I'm using VBA_MFX to estimate choice model parameters. Now I tapped into the following issue: I ran multiple simulations and VBA_MFX fits in a row (~ 360 times to test different models and a range of parameters). I noticed that the VBA_MFX inversion is getting slower and slower (starting from a few seconds up to >60min per run). If I restart MATLAB, the problem is gone. 'clear all' or 'close all' do not solve the problem.

Best,
Antonius

**Comment by lionel-rigoux** [comment]
Hi Antonius,

Which model are you trying to invert with MFX?
It would be nice if you could post a minmal code on https://gist.github.com/ so we can try to reproduce your problem.

Best

**Comment by awiehler** [comment]
Hi,
sorry for my late reply. I just came back to this... I'm fitting
discounting functions to choice data, nothing fancy. I could not upload
files so I attached them to the email. You might have to adjust the path in
the beginning of VBA_fit_multi_subject.m

I assume the problem might be related to the diagnostic windows opening...
I have not found an option to turn them off. I run Matlab itself
with  -nodisplay in the terminal, but the problem continues.

Let me know if I can help with anything.

Best,
Antonius

**Comment by lionel-rigoux** [comment]
Hey Antonius

This is a Github thread and answering to this email is logged into github. Because of this (I guess) I could not see the files you attached.
Please send me privately the code, or start a Gist. Please ensure to enclose all dependencies.
I’ll then try to reproduce your bug.

**Comment by awiehler** [comment]
done. (sent to your gmail).

**Comment by lionel-rigoux** [comment]
How should I organize all the folders and what should I change to run it?

**Comment by awiehler** [comment]
Hi, sorry not for beeing clear enough. Unzip everything.
"Die-hard-discounting" is the main folder, "main_exp" includes (simulated)
log files, "_output" priors for modeling. The main script to run is
VBA_fit_multi_subject.m. Folder locations in line 21-24 need to be
adjusted, depending on the location of the folders.

hope this helps.

Best,
Antonius

**Comment by lionel-rigoux** [comment]
I got the script running with no windows. For me, even the first files take way more than “few seconds” to run, as I am closer to 3min so far. I will let run overnight while logging the duration this if I can reproduce you bug.
Are you sure the lengthening is due to the repetition and not the specific parametrization you’re testing in later loops? Meaning, if you reverse the order of model inversion, do you still see an increase of duration or does it reverse?

**Comment by awiehler** [comment]
great, thanks for checking! Let me know what the result is. I will try the
inversion. how did you manage to supress the windows?

Best,
Antonius

**Comment by lionel-rigoux** [comment]
So far I’m just doin a close all /clc after each iteration to avoid crowding the memory. You should see with Jean (and whoever wrote the MFX function) about implementing a proper verbose/display switch.

BTW, could you ask/help Jean to switch his copy of the toolbox to the development branch, he’s started pushing frenetically directly to the master and that’s not good...

**Comment by awiehler** [comment]
Ouch, I could have done that. *facepalm* Great immediate fix!

I will speak to Jean tomorrow, he left already.

Best,
Antonius

**Comment by lionel-rigoux** [comment]
Hey Antonius,

Your script ran overnight and is till running. So far I’ve seen no consistent slowing of the inversion across the ~250 blocs than were inverted, one bloc taking between 150 and 350s. I guess the accumulation of windows was indeed the issue (it can be quite memory greedy).
I suggest that:
- you insert a clc and a close all between each block of MFX inversion
- ask Jean for a more elegant solution using a noDisplay and a verbose flag in the MFX (and please on the development branch)
- see if you still have the problem.
I am sure you could also make use of the parallel toolbox to speed the things a bit up.

Let me know if this solves your problem
Cheers
L

**Comment by awiehler** [comment]
Hi,
so I double checked. You had the right idea, closing the figures in every
loop iteration did the trick. The problem disappeared. I still not fully
understand it, I started Matlab with no graphical display and there was no
more than 1/3 of my RAM used, but anyway...

I could help with setting up a no display option for VBA_MFX if needed.

Thanks again for checking!

Best,
Antonius

**Comment by lionel-rigoux** [comment]
Solved with #50
