### ISSUE TITLE
interference between VBA and SPM

### ISSUE THREAD

**Issue by NicolasClairis** [MBB-team/VBA-toolbox#48]
It seems that some VBA functions have the same name as in SPM and interfere with SPM proper functionning. Everytime I was trying to launch my fMRI first level in SPM it wouldn't start mentionning some bug in spm_hrf.m and I struggled some time until finding where the bug came from but solved it by removing VBA from the path.

In the long-term I guess it would be good to use different names to avoid this but in the short term I'd recommend to avoid using both at the same time as they may interfere with each other.

**Comment by NicolasClairis** [comment]
I guess that the main issues will come from the "spm_code" folder and the two spm_sdcm_estimate functions + their dependencies
https://github.com/MBB-team/VBA-toolbox/tree/master/stats%26plots/spm_code
https://github.com/MBB-team/VBA-toolbox/blob/master/subfunctions/spm_sdcm_estimate.m
https://github.com/MBB-team/VBA-toolbox/blob/master/subfunctions/spm_sdcm_estimate2.m

**Comment by lionel-rigoux** [comment]
This issue has been solved by the pull request #43 which was already merged to the development branch (commit c50ae6ef0d0fd586e4a810425e4b84210b349c08). The master branch has also been updated in the last major update.
Update you toolbox and you should be fine.

**Comment by lionel-rigoux** [comment]
My bad, I've just seen that the master is still lagging behind. The master will be updated soon, but you can switch to the development branch in the meantine. Thanks for flaging the issue.

**Comment by NicolasClairis** [comment]
yes i had the last version of the toolbox indeed
So great! Thanks for fixing the problem!

**Comment by lionel-rigoux** [comment]
Fixed by #49 (in public branch)

**Comment by NicolasClairis** [comment]
great work! thanks!
