### ISSUE TITLE
VBA_orth checking for NaN values

### ISSUE THREAD

**Issue by NicolasClairis** [MBB-team/VBA-toolbox#64]
It would be good to add a line to check for NaN values in the VBA_orth function
Something like

if nonzeros( isnan(A) )
error('your matrix should not include any NaN value');
end

at the start of the script because otherwise any parasite NaN value will create a column full of NaN in the output possibly messing with other scripts afterwards.

**Comment by lionel-rigoux** [comment]
Fixed by 072682f74f885e9c79dac42573d0e32546a05606

**Comment by NicolasClairis** [comment]
Thanks!
