### ISSUE TITLE
Documentation of iQy

### ISSUE THREAD

**Issue by ezander** [MBB-team/VBA-toolbox#68]
In the documentation of the options for the priors it is said that iQy is the precision matrix of the observation error. As that is the inverse of the variance, then if the data scales with a factor of f, then iQy should scale by a factor of f^-2. All my experiments with the toolbox show however, that I need to scale iQy by f^-1in order to get equivalent results for scaled data, so for me it seems that iQy is rather a matrix square root of the precision matrix. Is that correct? If so, it would be nice to correct the documentation accordingly.

**Comment by lionel-rigoux** [comment]
Fixed by 072682f74f885e9c79dac42573d0e32546a05606
