### ISSUE TITLE
Deriving Volterra Kernels for (b)DCM

### ISSUE THREAD

**Issue by SRSteinkamp** [MBB-team/VBA-toolbox#70]
Dear all,

I realized for bDCM and DCM that Volterra Kernels are not derived for mixed observations (i.e. y matrices containing NaNs). 
Using VBA_nanvar in VBA_getVolterraKernels could remove this issue (see pull request #71). But I do not know if that leads to an invalid derivation of kernels...

Best, 
Simon

**Comment by lionel-rigoux** [comment]
This has been fixed by 417fd485d71a8a9bebfc6d333ee7f29adced82eb
