### ISSUE TITLE
Multinomial observation doesn't accept options.isYout

### ISSUE THREAD

**Issue by romainligneul** [MBB-team/VBA-toolbox#72]
Line 358 in VBA_updateDisplay generates an error whenever options.isYout contains non-zero values (for obvious reasons). 
Commenting the line solves the problem.

**Comment by lionel-rigoux** [comment]
Indeed, excluded points for categorical data are not taken into account properly in the display.
Commenting the line solves the issue but also remove the display of data points all together.

I included a more definitive fix in the branch I'm working on that solve a set of other performance issues in display functions. I will merge this branch onto the "development" one as soon as the tests are finished.

Thanks for the feedback!

**Comment by romainligneul** [comment]
You're welcome! Thanks for this excellent tool.

**Comment by lionel-rigoux** [comment]
This is now fixed in the development branch via cdf5d7f5b7469af5b54fa5b0ecea7e198d1c2994
